imports:
    - { resource: services_provider.yaml }

parameters:
    app_version: '%env(APP_VERSION)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $poleEmploiClientId: '%env(POLE_EMPLOI_CLIENT_ID)%'
            string $poleEmploiClientSecret: '%env(POLE_EMPLOI_CLIENT_SECRET)%'
            string $mailjetApiKey: '%env(MAILJET_API_KEY)%'
            string $mailjetApiSecretKey: '%env(MAILJET_API_SECRET_KEY)%'
            string $mailjetListId: '%env(MAILJET_CONTACT_LIST_ID)%'
            string $arbeitsagenturClientId: '%env(ARBEITSAGENTUR_CLIENT_ID)%'
            string $arbeitsagenturClientSecret: '%env(ARBEITSAGENTUR_CLIENT_SECRET)%'
            string $stripeApiKey: '%env(STRIPE_API_KEY)%'
            string $taxRateId: '%env(STRIPE_TAX_RATE_ID)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Provider/JobProvider.php'

    _instanceof:
        App\Provider\JobProviderInterface:
            tags: ['app.job_provider']
